FROM prefecthq/prefect:2.14.0-python3.10

# Install all flow dependencies in the base Python
RUN pip install --no-cache-dir \
        prefect==2.14.0 \
        kafka-python==2.0.2 \
        pandas==2.2.2 \
        pyarrow==18.1.0 \
        griffe==0.49.0

WORKDIR /opt/prefect/flows
